### ISSUE TITLE
react issue

### ISSUE THREAD

**Issue by drewvpham** [justdjango/django_project_boilerplate#9]
running npm i and npm start i run into the below issue:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.13.1
3 info using node@v8.1.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle django-react-boilerplate@0.3.0~prestart: django-react-boilerplate@0.3.0
6 info lifecycle django-react-boilerplate@0.3.0~start: django-react-boilerplate@0.3.0
7 verbose lifecycle django-react-boilerplate@0.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle django-react-boilerplate@0.3.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/drewpham/Desktop/projects/django-react-boilerplate/node_modules/.bin:/Users/drewpham/Desktop/projects/django-react-boilerplate/env/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/local/sbin:/Users/drewpham/.rvm/gems/ruby-2.3.1/bin:/Users/drewpham/.rvm/gems/ruby-2.3.1@global/bin:/Users/drewpham/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/drewpham/.rvm/bin
9 verbose lifecycle django-react-boilerplate@0.3.0~start: CWD: /Users/drewpham/Desktop/projects/django-react-boilerplate
10 silly lifecycle django-react-boilerplate@0.3.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle django-react-boilerplate@0.3.0~start: Returned: code: 1  signal: null
12 info lifecycle django-react-boilerplate@0.3.0~start: Failed to exec start script
13 verbose stack Error: django-react-boilerplate@0.3.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid django-react-boilerplate@0.3.0
15 verbose cwd /Users/drewpham/Desktop/projects/django-react-boilerplate
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.1.3
19 verbose npm  v6.13.1
20 error code ELIFECYCLE
21 error errno 1
22 error django-react-boilerplate@0.3.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the django-react-boilerplate@0.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by fleaz** [comment]
Hey @drewvpham ,
this is not the correct repository for your problem. You probably wan't to open your issue over here: [ustdjango/django-react-boilerplate](https://github.com/justdjango/django-react-boilerplate) :)
